### ISSUE TITLE
Fails to log at end of exiting application

### ISSUE THREAD

**Issue by quiffman** [GeoNet/log#5]
I'm not sure this is a bug per se, but it was slightly unexpected behaviour - any help here would be appreciated.

I have a short lived go application, that exits immediately after success. To monitor that success I decided to add a log line just before the end of the main function, but never saw the calls to log make it to logentries.

It seems to me like the application is exiting before the logentries write go process gets to do its thing.
By way of example, I can't get the following application to consistently send to logentries:
```
package main

import (
	_ "github.com/GeoNet/log/logentries"
	"log"
)

func main() {
	log.SetPrefix("log1 ")
	log.Print("Hello Logentries.")
}
```

But chuck a sleep delay in there and it works fine:
```
package main

import (
	_ "github.com/GeoNet/log/logentries"
	"log"
	"time"
)

func main() {
	log.SetPrefix("log2 ")
	log.Print("Hello Logentries.")
	time.Sleep(time.Duration(5) * time.Second)
}
```

Given the design "Uses a buffered chan to avoid blocking the application.", it's entirely possible this is expected behaviour. I just wasn't expecting it ;-)

Is there any sensible way I can force the log to flush, prior to exiting the application?

Assigning to Geoff, but help or suggestions from any other @GeoNet/sysdev-team members would also be appreciated.

**Comment by gclitheroe** [comment]
It certainly sounds like your getting caught by the message still be on the buffered chan when the exit happens.  There is no way for you to force a wait for this at the moment.

I don't especially want to add some defer that waits for the chan to empty and or handle signals.  Largely because I prefer a quick exit.  

If you do really want the log message to get there then a blocking logger would work e,g., https://github.com/bsphere/le_go or I could add a config parameter or another func here to do blocking logging?

If you want a function that blocks then we'd need to test if switching out the log writer still makes sense as it might change program behavior depending on the LOGENTRIES_TOKEN being set or not.  The downside being having a func `logentries.Print(string)` is pretty invasive in your app.

**Comment by quiffman** [comment]
Yup, understood.

"This isn't the logging library you're looking for", would have been a totally acceptable response.
Logging for two completely different reasons.

I was vaguely concerned that this might have the potential to hide issues with our existing apps, when (for example) dependent libraries call `log.Fatal(err)`.

**Comment by gclitheroe** [comment]
Could be a good reason to expose a logentries.Print that blocks and can be followed by an exit.

**Comment by quiffman** [comment]
I really don't know.

I suspect this requires a bit more thought than I can give it at the moment.
